### ISSUE TITLE
MST - can I tell it that not all dots are connected

### ISSUE THREAD

**Issue by ronnac** [yhpong/Scientific-Toolkit#2]
I use your wine example Test_MST for a set of data where some distances are very large (in fact : no connection exists between some of the nodes). However, the output shows them very close to some of the other nodes. Is there a way to input a distance matrix where some elements get for example -1, and that this is interpreted as "no connection exists"?
In other words can an MST have mutliple roots?

**Comment by yhpong** [comment]
Sorry I missed your comment for such a long time. Let me know if this is still an issue. The new graph classes now allow ingle edge manipulation, so you can delete an edge directly from a created MST. Let me know if you still need this and I will send you an example.

**Comment by yhpong** [comment]
Here is the demo file with comments inside, resave it as .xlsm to see it. With this you can create a MST and delete any arbitrary edge in it, which can be visualize as separate components. Hope it helps.
[MST_Test.xlsx](https://github.com/yhpong/Scientific-Toolkit/files/2599143/MST_Test.xlsx)
